insert into items (type, content, difficulty, tags) values
  ('sentence', 'I deployed the fix to production yesterday.', 1, array['past_tense', 'devops', 'ending_d']),
  ('sentence', 'I debugged the failing job before lunch.', 2, array['past_tense', 'devops', 'ending_d']),
  ('sentence', 'I configured the load balancer for the new service.', 2, array['past_tense', 'cloud', 'ending_d']),
  ('sentence', 'I merged the pull request after the tests passed.', 2, array['past_tense', 'devops', 'ending_d']),
  ('sentence', 'I reviewed the alert policy with the team.', 2, array['past_tense', 'devops', 'ending_d']),
  ('sentence', 'I fixed the cache issue in staging.', 1, array['past_tense', 'devops', 'ending_t']),
  ('sentence', 'I pushed the Docker image to the registry.', 1, array['past_tense', 'devops', 'ending_t']),
  ('sentence', 'I rolled back the release after the error rate increased.', 3, array['past_tense', 'devops', 'ending_t']),
  ('sentence', 'I monitored the database during the migration.', 2, array['past_tense', 'cloud', 'ending_d']),
  ('sentence', 'I scaled the worker pool during peak traffic.', 2, array['past_tense', 'cloud', 'ending_d']),
  ('minimal_pair', 'I walk every day. I walked yesterday.', 1, array['minimal_pair', 'past_tense', 'ending_t']),
  ('minimal_pair', 'I push code every morning. I pushed code yesterday.', 1, array['minimal_pair', 'past_tense', 'ending_t']),
  ('minimal_pair', 'I deploy on Monday. I deployed on Tuesday.', 1, array['minimal_pair', 'past_tense', 'ending_d']),
  ('minimal_pair', 'I review logs every day. I reviewed logs last night.', 2, array['minimal_pair', 'past_tense', 'ending_d']),
  ('minimal_pair', 'The job fails today. The job failed yesterday.', 2, array['minimal_pair', 'past_tense', 'ending_d']),
  ('sentence', 'I think the cache is broken.', 2, array['theta', 'devops']),
  ('sentence', 'The third thread timed out.', 3, array['theta', 'devops']),
  ('sentence', 'She checked the shell script.', 2, array['sh', 'ch', 'devops']),
  ('sentence', 'The change should ship after review.', 3, array['sh', 'ch', 'devops']),
  ('sentence', 'Which shard handled the checkout request?', 3, array['ch', 'sh', 'cloud']);
