insert into items (type, content, difficulty, tags) values
  ('sentence', 'I deployed the fix to production yesterday.', 1, array['past_tense', 'devops', 'ending_d']),
  ('sentence', 'I debugged the failing job before lunch.', 2, array['past_tense', 'devops', 'ending_d']),
  ('sentence', 'I configured the load balancer for the new service.', 2, array['past_tense', 'cloud', 'ending_d']),
  ('sentence', 'I merged the pull request after the tests passed.', 2, array['past_tense', 'devops', 'ending_d']),
  ('sentence', 'I reviewed the alert policy with the team.', 2, array['past_tense', 'devops', 'ending_d']),
  ('sentence', 'I fixed the cache issue in staging.', 1, array['past_tense', 'devops', 'ending_t']),
  ('sentence', 'I pushed the Docker image to the registry.', 1, array['past_tense', 'devops', 'ending_t']),
  ('sentence', 'I rolled back the release after the error rate increased.', 3, array['past_tense', 'devops', 'ending_t']),
  ('sentence', 'I monitored the database during the migration.', 2, array['past_tense', 'cloud', 'ending_d']),
  ('sentence', 'I scaled the worker pool during peak traffic.', 2, array['past_tense', 'cloud', 'ending_d']),
  ('minimal_pair', 'I walk every day. I walked yesterday.', 1, array['minimal_pair', 'past_tense', 'ending_t']),
  ('minimal_pair', 'I push code every morning. I pushed code yesterday.', 1, array['minimal_pair', 'past_tense', 'ending_t']),
  ('minimal_pair', 'I deploy on Monday. I deployed on Tuesday.', 1, array['minimal_pair', 'past_tense', 'ending_d']),
  ('minimal_pair', 'I review logs every day. I reviewed logs last night.', 2, array['minimal_pair', 'past_tense', 'ending_d']),
  ('minimal_pair', 'The job fails today. The job failed yesterday.', 2, array['minimal_pair', 'past_tense', 'ending_d']),
  ('sentence', 'I think the cache is broken.', 2, array['theta', 'devops']),
  ('sentence', 'The third thread timed out.', 3, array['theta', 'devops']),
  ('sentence', 'She checked the shell script.', 2, array['sh', 'ch', 'devops']),
  ('sentence', 'The change should ship after review.', 3, array['sh', 'ch', 'devops']),
  ('sentence', 'Which shard handled the checkout request?', 3, array['ch', 'sh', 'cloud']),
  ('sentence', 'I cooked rice and washed the dishes.', 1, array['daily', 'past_tense', 'ending_t', 'ending_d']),
  ('sentence', 'She cleaned the room and closed the windows.', 1, array['daily', 'past_tense', 'ending_d', 'plural_s']),
  ('sentence', 'I bought snacks for my friends.', 2, array['daily', 'ending_t', 'ending_s', 'plural_s']),
  ('sentence', 'The bus stops near my house.', 2, array['daily', 'ending_s', 'plural_s']),
  ('sentence', 'I watched three short shows last night.', 2, array['daily', 'ch', 'sh', 'theta', 'past_tense']),
  ('sentence', 'I booked a flight and packed two bags.', 2, array['travel', 'past_tense', 'ending_t', 'plural_s']),
  ('sentence', 'The hotel charged extra fees.', 2, array['travel', 'ch', 'past_tense', 'ending_d', 'plural_s']),
  ('sentence', 'I asked for directions at the station.', 2, array['travel', 'ending_t', 'ending_s', 'theta']),
  ('sentence', 'This beach has soft white sand.', 2, array['travel', 'theta', 'ch', 'sh', 'ending_d']),
  ('sentence', 'We changed seats before the plane took off.', 3, array['travel', 'ch', 'past_tense', 'ending_d', 'ending_s']),
  ('sentence', 'I joined the meeting five minutes late.', 1, array['work', 'meetings', 'past_tense', 'ending_d', 'ending_s']),
  ('sentence', 'Please share the charts after lunch.', 2, array['work', 'meetings', 'sh', 'ch', 'ending_s']),
  ('sentence', 'I discussed the next steps with the team.', 2, array['work', 'meetings', 'past_tense', 'ending_t', 'ending_s', 'theta']),
  ('sentence', 'The client asked three questions.', 2, array['work', 'meetings', 'ending_t', 'theta', 'ch', 'plural_s']),
  ('sentence', 'I finished the report and sent the slides.', 2, array['work', 'meetings', 'past_tense', 'sh', 'ending_t', 'ending_d', 'plural_s']),
  ('sentence', 'I worked on three projects last year.', 2, array['interviews', 'past_tense', 'ending_t', 'theta', 'plural_s']),
  ('sentence', 'I improved the process and reduced costs.', 3, array['interviews', 'past_tense', 'ending_d', 'ending_t', 'plural_s']),
  ('sentence', 'My strengths are ownership and clear communication.', 3, array['interviews', 'theta', 'sh']),
  ('sentence', 'I solved a production issue under pressure.', 3, array['interviews', 'past_tense', 'ending_d', 'sh']),
  ('sentence', 'I managed tasks across three teams.', 2, array['interviews', 'past_tense', 'ending_d', 'ending_s', 'theta']),
  ('sentence', 'I''m looking forward to our collaboration.', 2, array['work', 'meetings', 'sh', 'ch', 'general_fluency']),
  ('sentence', 'Could you please explain that in more detail?', 2, array['work', 'meetings', 'ch', 'sh', 'general_fluency']),
  ('sentence', 'I''ll get back to you as soon as possible.', 1, array['work', 'meetings', 'ending_t', 'ending_s', 'general_fluency']),
  ('sentence', 'Let''s touch base next week to discuss the progress.', 2, array['work', 'meetings', 'ch', 'sh', 'ending_s', 'general_fluency']),
  ('sentence', 'I appreciate your patience while we resolve this.', 3, array['work', 'meetings', 'sh', 'theta', 'general_fluency']),
  ('sentence', 'It''s been a pleasure meeting you today.', 1, array['social', 'sh', 'ch', 'general_fluency']),
  ('sentence', 'I''m currently working on a new feature for our app.', 2, array['work', 'devops', 'sh', 'ch', 'general_fluency']),
  ('sentence', 'Could you give me a hand with this task?', 1, array['daily', 'ending_d', 'ending_s', 'general_fluency']),
  ('sentence', 'I''m sorry, I didn''t quite catch that.', 1, array['daily', 'social', 'ch', 'ending_t', 'general_fluency']),
  ('sentence', 'That sounds like a great plan, let''s go for it.', 1, array['daily', 'social', 'ending_s', 'ending_t', 'general_fluency']),
  ('sentence', 'I usually drink coffee in the morning.', 1, array['daily', 'ending_s', 'ending_t', 'general_fluency']),
  ('sentence', 'She studies English every day to improve her skills.', 2, array['daily', 'ending_s', 'sh', 'general_fluency']),
  ('sentence', 'They visited many beautiful places during their vacation.', 2, array['travel', 'ending_d', 'plural_s', 'sh', 'general_fluency']),
  ('sentence', 'I''m thinking about going for a walk this afternoon.', 2, array['daily', 'theta', 'sh', 'general_fluency']),
  ('sentence', 'Can you tell me where the nearest supermarket is?', 2, array['travel', 'sh', 'ending_s', 'ending_t', 'general_fluency']),
  ('sentence', 'I''d like to order a large pizza with extra cheese.', 1, array['daily', 'shopping', 'ch', 'plural_s', 'general_fluency']),
  ('sentence', 'The weather has been quite unpredictable lately.', 2, array['daily', 'theta', 'sh', 'general_fluency']),
  ('sentence', 'I''m going to meet some friends for dinner tonight.', 1, array['social', 'ending_s', 'ending_t', 'general_fluency']),
  ('sentence', 'What do you like to do in your free time?', 1, array['social', 'ch', 'general_fluency']),
  ('sentence', 'I''ve been learning English for three years now.', 2, array['interviews', 'theta', 'plural_s', 'general_fluency']),
  ('sentence', 'We should focus on the most important features.', 2, array['work', 'meetings', 'sh', 'ch', 'plural_s', 'general_fluency']),
  ('sentence', 'I''ll finish the documentation by Friday.', 2, array['work', 'sh', 'ending_t', 'general_fluency']),
  ('sentence', 'The project reached its final stage last month.', 3, array['work', 'ch', 'sh', 'past_tense', 'ending_d', 'general_fluency']),
  ('sentence', 'Could you check if the server is running?', 1, array['devops', 'ch', 'sh', 'general_fluency']),
  ('sentence', 'I noticed a small bug in the latest version.', 2, array['devops', 'past_tense', 'ending_t', 'sh', 'general_fluency']),
  ('sentence', 'Please share your thoughts on this proposal.', 2, array['work', 'meetings', 'sh', 'theta', 'general_fluency']),
  ('sentence', 'We need to find a solution to this problem.', 2, array['work', 'sh', 'theta', 'general_fluency']),
  ('sentence', 'I''ll be available for a call this afternoon.', 1, array['work', 'meetings', 'sh', 'general_fluency']),
  ('sentence', 'It was a challenging but rewarding experience.', 3, array['interviews', 'ch', 'sh', 'ending_d', 'general_fluency']);
-- ESL Practice Sentences: 300 entries
-- Phonetic focus: ending_d, ending_t, ending_s, past_tense, plural_s, theta, sh, ch
-- Categories: work, social, daily, devops, general_fluency, interview

INSERT INTO items (type, content, difficulty, tags) VALUES

-- ============================================================
-- SECTION 1: WORK / PROFESSIONAL (sentences 1–80)
-- ============================================================

('sentence', 'I need to share this document before the deadline.', 1, array['work', 'ending_d', 'sh', 'general_fluency']),
('sentence', 'She pushed the latest changes to the shared branch.', 2, array['work', 'past_tense', 'sh', 'ending_d']),
('sentence', 'The third sprint ends this Friday without exception.', 2, array['work', 'theta', 'ending_d', 'ending_t']),
('sentence', 'Please check the attached files before you sign.', 2, array['work', 'ch', 'ending_d', 'ending_t']),
('sentence', 'We shipped the product on time and within budget.', 2, array['work', 'sh', 'past_tense', 'ending_d']),
('sentence', 'The manager asked each team to submit their reports.', 2, array['work', 'past_tense', 'ch', 'ending_t']),
('sentence', 'Both engineers fixed the bugs before the release.', 2, array['work', 'theta', 'past_tense', 'ending_d']),
('sentence', 'I think we should schedule a call this Thursday.', 1, array['work', 'theta', 'sh', 'ch']),
('sentence', 'The sales figures matched our third-quarter targets.', 3, array['work', 'ending_d', 'theta', 'ending_t']),
('sentence', 'He reached out to the client and shared a proposal.', 2, array['work', 'ch', 'ending_d', 'sh']),
('sentence', 'This task requires attention to detail and focus.', 2, array['work', 'ending_t', 'sh', 'ending_s']),
('sentence', 'I highlighted the risks in the project checklist.', 2, array['work', 'past_tense', 'sh', 'ch']),
('sentence', 'The budget has increased by thirty percent this year.', 2, array['work', 'past_tense', 'theta', 'ending_t']),
('sentence', 'She scheduled three workshops for the entire team.', 2, array['work', 'past_tense', 'sh', 'theta']),
('sentence', 'The patch was tested and deployed to production.', 2, array['work', 'past_tense', 'ending_d', 'ending_t']),
('sentence', 'We discussed the approach and chose the best solution.', 2, array['work', 'past_tense', 'ch', 'sh']),
('sentence', 'The checklist should be finished by end of shift.', 2, array['work', 'ch', 'sh', 'ending_d']),
('sentence', 'I appreciate the enthusiasm each person has shown.', 2, array['work', 'sh', 'ch', 'ending_d']),
('sentence', 'He shared three insights that changed our strategy.', 2, array['work', 'sh', 'theta', 'past_tense']),
('sentence', 'The latest dashboard shows the most recent trends.', 2, array['work', 'sh', 'ending_t', 'ending_s']),
('sentence', 'She reached the project milestone ahead of schedule.', 2, array['work', 'ch', 'ending_d', 'sh']),
('sentence', 'I switched the environment variables before the test.', 2, array['work', 'past_tense', 'ending_d', 'ending_t']),
('sentence', 'The architect proposed changes to the third module.', 3, array['work', 'theta', 'past_tense', 'ending_d']),
('sentence', 'Our stakeholders expect results by this Thursday.', 2, array['work', 'ending_t', 'theta', 'ending_s']),
('sentence', 'I pushed the hotfix and notified the on-call engineer.', 2, array['work', 'past_tense', 'ending_d', 'ending_t']),
('sentence', 'The team exceeded expectations during the last sprint.', 2, array['work', 'past_tense', 'ending_d', 'ending_t']),
('sentence', 'She showed remarkable leadership throughout the project.', 3, array['work', 'sh', 'ending_d', 'past_tense']),
('sentence', 'I reached a conclusion after checking all the facts.', 2, array['work', 'ch', 'ending_d', 'past_tense']),
('sentence', 'This approach addresses the root cause of the issues.', 2, array['work', 'ch', 'ending_d', 'ending_s']),
('sentence', 'The client signed the contract without any changes.', 2, array['work', 'past_tense', 'ending_d', 'ch']),
('sentence', 'Both services crashed after the scheduled maintenance.', 3, array['work', 'theta', 'past_tense', 'ending_d']),
('sentence', 'She achieved her targets through consistent hard work.', 2, array['work', 'past_tense', 'ending_t', 'theta']),
('sentence', 'I need to think through this before the next standup.', 2, array['work', 'theta', 'ending_d', 'ending_t']),
('sentence', 'The latest shift in strategy shifted our priorities.', 3, array['work', 'sh', 'past_tense', 'ending_d']),
('sentence', 'He finished the analysis ahead of the third checkpoint.', 3, array['work', 'sh', 'ch', 'theta']),
('sentence', 'We attached the revised draft to the email thread.', 2, array['work', 'past_tense', 'ending_d', 'theta']),
('sentence', 'The shortlist of candidates has been shared with HR.', 2, array['work', 'sh', 'past_tense', 'ending_d']),
('sentence', 'She switched to a different approach after the feedback.', 2, array['work', 'sh', 'ch', 'past_tense']),
('sentence', 'The archived logs showed no signs of the issue.', 2, array['work', 'sh', 'past_tense', 'ending_d']),
('sentence', 'He wished the team good luck and thanked them all.', 1, array['work', 'sh', 'theta', 'past_tense']),

-- INTERVIEW SENTENCES
('sentence', 'I thrive in fast-paced environments where I can learn.', 2, array['interview', 'theta', 'ending_d', 'ending_t']),
('sentence', 'In my last role, I led a cross-functional team of six.', 2, array['interview', 'ending_d', 'past_tense', 'ending_t']),
('sentence', 'I believe that consistent effort leads to lasting results.', 2, array['interview', 'theta', 'ending_d', 'ending_t']),
('sentence', 'I enjoy challenges that push me outside my comfort zone.', 2, array['interview', 'ch', 'ending_d', 'ending_t']),
('sentence', 'My greatest strength is turning ideas into action.', 2, array['interview', 'theta', 'ending_t', 'ending_d']),
('sentence', 'I choose to see each setback as a chance to improve.', 2, array['interview', 'ch', 'ending_t', 'past_tense']),
('sentence', 'I appreciate feedback and use it to sharpen my skills.', 2, array['interview', 'sh', 'ending_d', 'ending_t']),
('sentence', 'I achieved this by breaking the task into smaller steps.', 2, array['interview', 'past_tense', 'ending_d', 'ending_t']),
('sentence', 'I switched careers because I wanted a deeper challenge.', 2, array['interview', 'past_tense', 'ch', 'ending_d']),
('sentence', 'I have shipped products that serve thousands of users.', 2, array['interview', 'sh', 'ending_d', 'ending_t']),
('sentence', 'The most difficult project taught me to think strategically.', 3, array['interview', 'theta', 'past_tense', 'ending_d']),
('sentence', 'I reached out to the stakeholders to clarify the brief.', 2, array['interview', 'ch', 'past_tense', 'ending_d']),
('sentence', 'I think my experience makes me a strong match for this role.', 2, array['interview', 'theta', 'ch', 'ending_d']),
('sentence', 'I helped reduce costs without affecting service quality.', 3, array['interview', 'past_tense', 'sh', 'ending_t']),
('sentence', 'I enjoy helping others reach their professional goals.', 2, array['interview', 'ch', 'ending_d', 'sh']),

-- REMOTE WORK
('sentence', 'Could you share your screen so we can check the bug?', 1, array['work', 'sh', 'ch', 'ending_d']),
('sentence', 'I will be on a different shift this Thursday and Friday.', 1, array['work', 'sh', 'theta', 'ending_d']),
('sentence', 'Please mute yourself unless you wish to speak.', 1, array['work', 'sh', 'ending_d', 'ending_t']),
('sentence', 'The third meeting of the day starts in five minutes.', 1, array['work', 'theta', 'ending_d', 'ending_t']),
('sentence', 'I pushed the changes and the checks passed without issues.', 2, array['work', 'past_tense', 'ch', 'ending_d']),
('sentence', 'She finished the first draft and shared it in the channel.', 2, array['work', 'sh', 'past_tense', 'ending_d', 'ch']),
('sentence', 'My internet was choppy throughout the entire call.', 2, array['work', 'ch', 'theta', 'past_tense']),
('sentence', 'I thought the meeting was scheduled for this Thursday.', 2, array['work', 'theta', 'sh', 'past_tense']),
('sentence', 'Let me reshare the link — the last one might have expired.', 2, array['work', 'sh', 'ending_d', 'past_tense']),
('sentence', 'The async updates help the distributed team stay aligned.', 3, array['work', 'sh', 'ending_d', 'ending_t']),
('sentence', 'I checked my schedule and the slot on Thursday works fine.', 1, array['work', 'ch', 'sh', 'theta']),
('sentence', 'The standups have shifted to thirty minutes per session.', 2, array['work', 'sh', 'theta', 'past_tense']),
('sentence', 'She shared a short summary of what was discussed.', 1, array['work', 'sh', 'past_tense', 'ending_d']),
('sentence', 'The branch was checked out and the tests were initiated.', 2, array['work', 'ch', 'past_tense', 'ending_d']),
('sentence', 'He wished he had pushed the fix before the incident.', 2, array['work', 'sh', 'past_tense', 'ending_d']),
('sentence', 'I think asynchronous communication suits this team best.', 3, array['work', 'theta', 'sh', 'ending_t']),
('sentence', 'The chat logs showed the sequence of events clearly.', 2, array['work', 'sh', 'ch', 'ending_d']),
('sentence', 'I refreshed the dashboard and the changes appeared.', 2, array['work', 'sh', 'ch', 'past_tense']),
('sentence', 'She chose to address the issue in the public thread.', 2, array['work', 'ch', 'ending_d', 'sh']),
('sentence', 'Both shifts reported the same issue with the third service.', 3, array['work', 'sh', 'theta', 'past_tense']),
('sentence', 'We chose to ship a smaller feature set in this release.', 2, array['work', 'sh', 'ch', 'ending_t']),
('sentence', 'The architect suggested a short-term and a long-term fix.', 3, array['work', 'past_tense', 'ending_d', 'sh']),
('sentence', 'I wish I had caught that edge case before the hotfix.', 2, array['work', 'sh', 'ch', 'past_tense']),

-- ============================================================
-- SECTION 2: DEVOPS / TECH (sentences 81–130)
-- ============================================================

('sentence', 'The deployment script failed on the third attempt.', 2, array['devops', 'past_tense', 'theta', 'ending_d']),
('sentence', 'We switched the load balancer to a different region.', 2, array['devops', 'past_tense', 'ending_d', 'sh']),
('sentence', 'The shared cluster hosts six different microservices.', 3, array['devops', 'sh', 'ending_d', 'ending_t']),
('sentence', 'I think the pod crashed because the health check failed.', 2, array['devops', 'theta', 'ch', 'past_tense']),
('sentence', 'The patch for the authentication bug was pushed last night.', 2, array['devops', 'past_tense', 'sh', 'ending_d']),
('sentence', 'She configured the third node without the shared volume.', 3, array['devops', 'past_tense', 'theta', 'sh']),
('sentence', 'The workflow was cached and the build finished in seconds.', 2, array['devops', 'past_tense', 'sh', 'ending_d']),
('sentence', 'He checked whether the secrets were rotated this month.', 2, array['devops', 'ch', 'past_tense', 'ending_d']),
('sentence', 'The chart showed a spike at exactly three in the morning.', 2, array['devops', 'sh', 'ch', 'ending_d']),
('sentence', 'I fetched the logs and found the root cause of the crash.', 2, array['devops', 'ch', 'past_tense', 'ending_d']),
('sentence', 'The throttling threshold was changed by the third engineer.', 3, array['devops', 'theta', 'past_tense', 'ending_d', 'ch']),
('sentence', 'She architected the solution so each service could scale.', 3, array['devops', 'past_tense', 'sh', 'ch']),
('sentence', 'The shared storage bucket reached its capacity limit.', 2, array['devops', 'sh', 'ch', 'ending_d', 'ending_t']),
('sentence', 'Both the staging and the production checks passed.', 2, array['devops', 'theta', 'ch', 'past_tense']),
('sentence', 'The scheduled job runs each night at three.', 1, array['devops', 'sh', 'ch', 'theta']),
('sentence', 'This is the third time the webhook timed out this week.', 2, array['devops', 'theta', 'ending_d', 'past_tense']),
('sentence', 'The charts indicate that throughput has doubled.', 2, array['devops', 'ch', 'theta', 'ending_d']),
('sentence', 'I notched the threshold up after the load test results.', 3, array['devops', 'theta', 'past_tense', 'ending_d']),
('sentence', 'The catch block was not reached during the integration test.', 2, array['devops', 'ch', 'ending_d', 'past_tense']),
('sentence', 'She chose to use short-lived credentials for this pipeline.', 3, array['devops', 'sh', 'ch', 'ending_d']),
('sentence', 'The batch jobs finished at the same time on both clusters.', 2, array['devops', 'ch', 'past_tense', 'ending_d']),
('sentence', 'I searched the logs but found nothing before the crash.', 2, array['devops', 'sh', 'ch', 'past_tense']),
('sentence', 'We shifted the cache strategy after the third outage.', 2, array['devops', 'sh', 'ch', 'theta']),
('sentence', 'The shared namespace caused a conflict between both services.', 3, array['devops', 'sh', 'past_tense', 'ending_d']),
('sentence', 'I wish the circuit breaker had been tested beforehand.', 2, array['devops', 'sh', 'ch', 'past_tense']),
('sentence', 'He attached the trace ID to help with the investigation.', 2, array['devops', 'ch', 'ending_d', 'past_tense']),
('sentence', 'The third pipeline was archived after the feature shipped.', 2, array['devops', 'theta', 'sh', 'past_tense']),
('sentence', 'I checked the timestamps and matched them to the outage window.', 3, array['devops', 'ch', 'past_tense', 'ending_d']),
('sentence', 'Each node refreshed its state on schedule without issues.', 3, array['devops', 'sh', 'ch', 'ending_d']),
('sentence', 'The chaos test showed a weakness in the third failover path.', 3, array['devops', 'sh', 'ch', 'theta']),
('sentence', 'She pushed the shim to fix the shared library conflict.', 3, array['devops', 'sh', 'past_tense', 'ending_d']),
('sentence', 'The thread count spiked before the process crashed.', 2, array['devops', 'theta', 'ch', 'past_tense']),
('sentence', 'Both the sandbox and the production builds passed.', 2, array['devops', 'past_tense', 'ending_d', 'sh']),
('sentence', 'He scheduled the change window for this Thursday night.', 2, array['devops', 'sh', 'ch', 'theta']),
('sentence', 'The health checks passed but the pod still restarted.', 2, array['devops', 'ch', 'past_tense', 'ending_t']),
('sentence', 'I fetched the fresh config and the issue resolved itself.', 2, array['devops', 'sh', 'ch', 'past_tense']),
('sentence', 'The threshold for alerting was adjusted after the first incident.', 3, array['devops', 'theta', 'past_tense', 'ending_d']),
('sentence', 'She wished she had enabled the feature flag before the release.', 2, array['devops', 'sh', 'past_tense', 'ending_d']),
('sentence', 'The shared volume was attached to the correct namespace.', 2, array['devops', 'sh', 'ch', 'past_tense']),
('sentence', 'I switched the branch and rebuilt without the deprecated flag.', 3, array['devops', 'sh', 'ch', 'past_tense']),
('sentence', 'The scheduled shutdown triggered earlier than expected.', 3, array['devops', 'sh', 'ch', 'past_tense']),
('sentence', 'Both checks finished before the third deployment attempt.', 3, array['devops', 'theta', 'ch', 'past_tense']),
('sentence', 'The caches were flushed and the search index was rebuilt.', 3, array['devops', 'sh', 'ch', 'past_tense']),
('sentence', 'She architected a solution that avoids a third-party lock-in.', 3, array['devops', 'ch', 'theta', 'ending_d']),
('sentence', 'The runbook was not checked before the change was deployed.', 3, array['devops', 'ch', 'past_tense', 'ending_d']),
('sentence', 'I noticed the thread was exhausted before the timeout hit.', 3, array['devops', 'theta', 'ch', 'past_tense']),
('sentence', 'The shared cache warmed up and throughput stabilized.', 3, array['devops', 'sh', 'ch', 'theta']),
('sentence', 'He watched the metrics and confirmed the fix had worked.', 2, array['devops', 'ch', 'past_tense', 'ending_d']),
('sentence', 'The fetch request timed out after the third retry.', 2, array['devops', 'theta', 'ch', 'past_tense']),
('sentence', 'She launched the fix without shutting down the cluster.', 3, array['devops', 'sh', 'ch', 'ending_d']),

-- ============================================================
-- SECTION 3: SOCIAL / DAILY (sentences 131–210)
-- ============================================================

('sentence', 'Could I get a glass of water, please?', 1, array['social', 'ending_d', 'ending_t', 'general_fluency']),
('sentence', 'I would like to check out around eleven, please.', 1, array['social', 'ch', 'ending_d', 'ending_t']),
('sentence', 'Thank you so much for your help today.', 1, array['social', 'theta', 'ending_d', 'general_fluency']),
('sentence', 'Could you show me where the nearest cash machine is?', 1, array['social', 'sh', 'ending_d', 'ending_t']),
('sentence', 'I think this dish tastes better with fresh chilies.', 1, array['social', 'theta', 'sh', 'ch']),
('sentence', 'She chose the chocolate cake for her birthday treat.', 1, array['social', 'ch', 'past_tense', 'ending_t']),
('sentence', 'He thanked the chef personally for the amazing meal.', 1, array['social', 'theta', 'ch', 'past_tense']),
('sentence', 'I usually order the grilled fish on Thursdays.', 1, array['social', 'theta', 'sh', 'ending_d']),
('sentence', 'The restaurant is just three blocks from this street.', 1, array['social', 'theta', 'ending_t', 'sh']),
('sentence', 'Could you check if there is a table for three, please?', 1, array['social', 'ch', 'theta', 'ending_d']),
('sentence', 'I finished my lunch and asked for the bill.', 1, array['social', 'past_tense', 'sh', 'ending_d']),
('sentence', 'She shared her dessert with the whole group.', 1, array['social', 'sh', 'past_tense', 'ending_d']),
('sentence', 'The shop around the corner has fresh bread every morning.', 1, array['social', 'sh', 'ch', 'ending_d']),
('sentence', 'He rushed to the pharmacy to get the prescription filled.', 2, array['social', 'sh', 'ch', 'past_tense']),
('sentence', 'I thought the cheapest option was on the third shelf.', 2, array['social', 'theta', 'ch', 'sh']),
('sentence', 'She wished him a happy birthday and handed him a gift.', 1, array['social', 'sh', 'past_tense', 'ending_d']),
('sentence', 'He changed his shoes before stepping outside.', 1, array['social', 'sh', 'ch', 'past_tense']),
('sentence', 'I matched the dress with a short blazer for the occasion.', 2, array['social', 'sh', 'ch', 'past_tense']),
('sentence', 'Could you switch the channel to the sports broadcast?', 2, array['social', 'ch', 'sh', 'ending_d']),
('sentence', 'The third floor is where they sell children''s clothing.', 2, array['social', 'theta', 'sh', 'ch']),
('sentence', 'She caught the last bus home and reached safely.', 2, array['social', 'ch', 'past_tense', 'ending_d']),
('sentence', 'I showed them the shortest path through the market.', 2, array['social', 'sh', 'theta', 'past_tense']),
('sentence', 'He watched three episodes before going to sleep.', 1, array['social', 'theta', 'ch', 'past_tense']),
('sentence', 'She polished her shoes and then headed out.', 1, array['social', 'sh', 'past_tense', 'ending_d']),
('sentence', 'I reached out and asked if she needed any help.', 1, array['social', 'ch', 'ending_d', 'past_tense']),
('sentence', 'He shared his thoughts over a short coffee break.', 1, array['social', 'sh', 'theta', 'ch']),
('sentence', 'The children chased each other through the park.', 1, array['social', 'ch', 'past_tense', 'theta']),
('sentence', 'I chose a fresh salad instead of the fried option.', 1, array['social', 'sh', 'ch', 'past_tense']),
('sentence', 'She checked the weather before she left the house.', 1, array['social', 'ch', 'sh', 'past_tense']),
('sentence', 'He stretched after the workout and felt refreshed.', 2, array['social', 'sh', 'ch', 'past_tense']),
('sentence', 'I think this city is the best place to watch the sunset.', 1, array['social', 'theta', 'ch', 'ending_t']),
('sentence', 'She flipped through the magazine while waiting.', 2, array['social', 'sh', 'past_tense', 'ending_d']),
('sentence', 'He wished he had chosen the other dish at the restaurant.', 2, array['social', 'sh', 'ch', 'past_tense']),
('sentence', 'The children shared the chocolate equally.', 1, array['social', 'ch', 'sh', 'past_tense']),
('sentence', 'I washed the dishes while she finished setting the table.', 1, array['social', 'sh', 'ch', 'past_tense']),
('sentence', 'She bought fresh vegetables at the market this morning.', 1, array['social', 'sh', 'ending_d', 'past_tense']),
('sentence', 'He thanked the shopkeeper and wished her a good day.', 1, array['social', 'theta', 'sh', 'ch']),
('sentence', 'I asked for a fresh towel and the staff brought one quickly.', 1, array['social', 'sh', 'ch', 'past_tense']),
('sentence', 'She showed the photos she had taken during the trip.', 1, array['social', 'sh', 'theta', 'past_tense']),
('sentence', 'The flight was delayed, but we finally reached the hotel.', 2, array['social', 'past_tense', 'ending_d', 'theta']),
('sentence', 'He chose to try the spicy noodles even though they were hot.', 2, array['social', 'ch', 'theta', 'past_tense']),
('sentence', 'I switched phones because the battery kept draining fast.', 2, array['social', 'ch', 'past_tense', 'ending_d']),
('sentence', 'She reached the finish line and the crowd cheered loudly.', 2, array['social', 'ch', 'ending_d', 'past_tense']),
('sentence', 'The children watched a short film about ocean life.', 1, array['social', 'ch', 'sh', 'theta']),
('sentence', 'I polished the shelf and arranged the books neatly.', 1, array['social', 'sh', 'past_tense', 'ending_d']),
('sentence', 'He rushed through breakfast and nearly missed the bus.', 2, array['social', 'sh', 'ch', 'past_tense']),
('sentence', 'She shared the recipe with her friends after the dinner.', 1, array['social', 'sh', 'ch', 'past_tense']),
('sentence', 'I thanked the host and helped wash the dishes afterward.', 1, array['social', 'theta', 'sh', 'past_tense']),
('sentence', 'He checked the expiry date on the milk before using it.', 1, array['social', 'ch', 'past_tense', 'ending_d']),
('sentence', 'The shelter provided food and clothing for those in need.', 2, array['social', 'sh', 'theta', 'ending_d']),
('sentence', 'She achieved her fitness goal without joining a gym.', 2, array['social', 'sh', 'past_tense', 'ending_d']),
('sentence', 'He notched up a third win at the chess championship.', 3, array['social', 'theta', 'ch', 'ending_d']),
('sentence', 'I wished my neighbour good luck on her job interview.', 1, array['social', 'sh', 'ending_d', 'past_tense']),
('sentence', 'She brought fresh flowers and placed them on the shelf.', 1, array['social', 'sh', 'past_tense', 'ending_d']),
('sentence', 'He watched the match and cheered with the crowd.', 1, array['social', 'sh', 'ch', 'past_tense']),
('sentence', 'I chose the shortest route to avoid the traffic.', 1, array['social', 'sh', 'ch', 'ending_d']),
('sentence', 'She stretched and breathed deeply after the long shift.', 2, array['social', 'sh', 'theta', 'past_tense']),
('sentence', 'The children reached the beach before noon and had a blast.', 2, array['social', 'ch', 'theta', 'past_tense']),
('sentence', 'He wished the situation could have been different.', 2, array['social', 'sh', 'past_tense', 'ending_d']),
('sentence', 'I switched to a shorter commute after the third month.', 2, array['social', 'sh', 'ch', 'theta']),
('sentence', 'She thanked the chef and said the fish was cooked perfectly.', 2, array['social', 'theta', 'sh', 'ch']),
('sentence', 'He refreshed his memory by rereading the third chapter.', 2, array['social', 'sh', 'ch', 'theta']),
('sentence', 'I packed the essentials and shipped the boxes ahead.', 2, array['social', 'sh', 'ch', 'past_tense']),
('sentence', 'She checked the map and chose the third exit on the roundabout.', 2, array['social', 'ch', 'theta', 'past_tense']),
('sentence', 'He thanked the shop assistant and walked out satisfied.', 1, array['social', 'theta', 'sh', 'past_tense']),
('sentence', 'The children each chose a book from the shelf.', 1, array['social', 'ch', 'sh', 'past_tense']),
('sentence', 'I shared the last slice with whoever was still hungry.', 2, array['social', 'sh', 'past_tense', 'ending_d']),
('sentence', 'She rushed out to catch the shuttle before it left.', 2, array['social', 'sh', 'ch', 'past_tense']),
('sentence', 'He reached into his pocket and offered her the change.', 1, array['social', 'ch', 'ending_d', 'past_tense']),
('sentence', 'I stretched the truth a little, but I meant no harm.', 2, array['social', 'theta', 'sh', 'ending_d']),
('sentence', 'She watched the chef toss the noodles with great skill.', 2, array['social', 'sh', 'ch', 'theta']),
('sentence', 'He matched his shirt with a fresh pair of chinos.', 1, array['social', 'sh', 'ch', 'past_tense']),
('sentence', 'I thanked them and checked if there was anything else needed.', 1, array['social', 'theta', 'ch', 'past_tense']),
('sentence', 'She showed me the best spot to watch the fireworks.', 1, array['social', 'sh', 'theta', 'past_tense']),
('sentence', 'He fetched a fresh glass of water without being asked.', 1, array['social', 'sh', 'past_tense', 'ending_d']),
('sentence', 'The shuttle schedule shows three trips each hour.', 2, array['social', 'sh', 'ch', 'theta']),
('sentence', 'I reached the top shelf and handed her the jar.', 1, array['social', 'ch', 'sh', 'past_tense']),
('sentence', 'She pushed through the crowd and reached the front.', 2, array['social', 'ch', 'sh', 'past_tense']),
('sentence', 'He thanked each guest personally as they arrived.', 1, array['social', 'theta', 'ch', 'past_tense']),

-- ============================================================
-- SECTION 4: GENERAL FLUENCY / IDIOMS / TRANSITIONS (211–300)
-- ============================================================

('sentence', 'On the other hand, there are some valid points worth considering.', 1, array['general_fluency', 'theta', 'ending_d', 'ending_t']),
('sentence', 'To be honest, I think this needs a bit more thought.', 1, array['general_fluency', 'theta', 'ending_d', 'ending_t']),
('sentence', 'That being said, I still believe we are on the right track.', 2, array['general_fluency', 'theta', 'ending_d', 'ending_t']),
('sentence', 'At the end of the day, results are what matter the most.', 1, array['general_fluency', 'theta', 'ending_d', 'ending_t']),
('sentence', 'In other words, we need to ship it and gather real feedback.', 2, array['general_fluency', 'sh', 'ending_d', 'theta']),
('sentence', 'It goes without saying that trust is the foundation of teamwork.', 2, array['general_fluency', 'theta', 'ending_d', 'ending_t']),
('sentence', 'All things considered, this was the best outcome we could achieve.', 2, array['general_fluency', 'theta', 'ch', 'ending_d']),
('sentence', 'That said, the third option still deserves a closer look.', 2, array['general_fluency', 'theta', 'ending_d', 'ending_t']),
('sentence', 'First and foremost, I want to thank everyone for their effort.', 2, array['general_fluency', 'theta', 'ending_d', 'ending_t']),
('sentence', 'In short, the changes helped and the results speak for themselves.', 2, array['general_fluency', 'sh', 'ch', 'ending_d']),
('sentence', 'To sum it up, we should prioritize the most critical issues first.', 2, array['general_fluency', 'sh', 'theta', 'ending_t']),
('sentence', 'Not to mention the fact that the third attempt always matters.', 2, array['general_fluency', 'theta', 'ending_d', 'ending_t']),
('sentence', 'In fact, the shift happened faster than anyone had anticipated.', 2, array['general_fluency', 'sh', 'past_tense', 'ending_d']),
('sentence', 'More importantly, we need to think about the long-term effects.', 2, array['general_fluency', 'theta', 'ending_t', 'ending_d']),
('sentence', 'As a result, the team achieved the targets ahead of schedule.', 2, array['general_fluency', 'sh', 'ch', 'past_tense']),
('sentence', 'Having said that, I think the challenges are still worth addressing.', 3, array['general_fluency', 'theta', 'sh', 'ch']),
('sentence', 'With that in mind, let us choose the most practical path forward.', 2, array['general_fluency', 'theta', 'ch', 'ending_d']),
('sentence', 'From my perspective, sharing feedback early is always beneficial.', 2, array['general_fluency', 'sh', 'theta', 'ending_d']),
('sentence', 'By and large, the third quarter showed strong improvements.', 2, array['general_fluency', 'theta', 'sh', 'ending_d']),
('sentence', 'In the long run, consistency beats short bursts of effort.', 2, array['general_fluency', 'sh', 'ending_t', 'ending_d']),
('sentence', 'This is easier said than done, but the effort is worthwhile.', 2, array['general_fluency', 'sh', 'theta', 'ending_d']),
('sentence', 'I would rather choose a difficult truth than a comfortable shortcut.', 3, array['general_fluency', 'ch', 'sh', 'theta']),
('sentence', 'It is worth noting that the shift in tone changed everything.', 2, array['general_fluency', 'sh', 'theta', 'ch']),
('sentence', 'On reflection, I think the chosen approach was the right one.', 2, array['general_fluency', 'theta', 'sh', 'ch']),
('sentence', 'To be fair, both sides have a point that should be considered.', 2, array['general_fluency', 'theta', 'ending_d', 'ending_t']),
('sentence', 'Needless to say, the third proposal was the strongest.', 2, array['general_fluency', 'theta', 'sh', 'ending_d']),
('sentence', 'At first glance, the chart looks good but the details matter.', 2, array['general_fluency', 'sh', 'ch', 'theta']),
('sentence', 'I know it sounds challenging, but I think we can manage it.', 2, array['general_fluency', 'sh', 'ch', 'theta']),
('sentence', 'On balance, the benefits outweigh the risks in the third phase.', 3, array['general_fluency', 'theta', 'sh', 'ending_d']),
('sentence', 'To put it differently, the problem is not the cost but the method.', 2, array['general_fluency', 'theta', 'ending_d', 'ending_t']),
('sentence', 'That is to say, we should share the workload more evenly.', 2, array['general_fluency', 'sh', 'theta', 'ending_d']),
('sentence', 'This hits the nail on the head — the issue was the third handoff.', 3, array['general_fluency', 'theta', 'sh', 'ending_d']),
('sentence', 'I think it is safe to say that the team has grown significantly.', 2, array['general_fluency', 'theta', 'sh', 'ending_d']),
('sentence', 'Even so, we should not rush the decision without enough data.', 2, array['general_fluency', 'sh', 'ending_d', 'ending_t']),
('sentence', 'Putting it bluntly, the third version was much stronger.', 2, array['general_fluency', 'theta', 'sh', 'ending_d']),
('sentence', 'To be clear, this change was thoroughly tested before release.', 2, array['general_fluency', 'theta', 'ch', 'past_tense']),
('sentence', 'It is not so much about the speed as the direction.', 2, array['general_fluency', 'sh', 'theta', 'ending_d']),
('sentence', 'All in all, this has been a challenging but rewarding journey.', 2, array['general_fluency', 'theta', 'ch', 'ending_d']),
('sentence', 'The bottom line is that we need to ship this by Thursday.', 2, array['general_fluency', 'sh', 'theta', 'ending_d']),
('sentence', 'Without a doubt, the third approach is the most scalable.', 2, array['general_fluency', 'theta', 'sh', 'ending_d']),
('sentence', 'To add to that, the architecture she chose is elegant.', 2, array['general_fluency', 'sh', 'ch', 'theta']),
('sentence', 'This is not the end but rather the beginning of the shift.', 2, array['general_fluency', 'sh', 'theta', 'ending_d']),
('sentence', 'Broadly speaking, the third option checks all the boxes.', 2, array['general_fluency', 'sh', 'ch', 'theta']),
('sentence', 'I think it is worth emphasizing that this is just a draft.', 2, array['general_fluency', 'theta', 'sh', 'ending_t']),
('sentence', 'Things are not always as they seem on the surface.', 1, array['general_fluency', 'theta', 'sh', 'ending_d']),
('sentence', 'I had not thought of it from that angle — thank you.', 1, array['general_fluency', 'theta', 'ending_d', 'ending_t']),
('sentence', 'Once you put it that way, the approach makes much more sense.', 2, array['general_fluency', 'theta', 'sh', 'ch']),
('sentence', 'Truth be told, the third draft was the most polished.', 2, array['general_fluency', 'theta', 'sh', 'ending_d']),
('sentence', 'By the same token, consistency in communication is key.', 2, array['general_fluency', 'theta', 'ch', 'ending_d']),
('sentence', 'In a nutshell, the shift toward automation has changed everything.', 2, array['general_fluency', 'sh', 'theta', 'ch']),
('sentence', 'That is a fair point, but I still think we need more data.', 1, array['general_fluency', 'theta', 'ending_d', 'ending_t']),
('sentence', 'I would not go that far, but I do think it helps.', 1, array['general_fluency', 'theta', 'ending_d', 'ending_t']),
('sentence', 'At this point, I think the third iteration is strong enough.', 2, array['general_fluency', 'theta', 'sh', 'ending_d']),
('sentence', 'I stand by the decision even though it was not the easiest choice.', 2, array['general_fluency', 'theta', 'sh', 'ch']),
('sentence', 'With respect to the changes, I think we should revisit the third one.', 3, array['general_fluency', 'theta', 'ch', 'sh']),
('sentence', 'As far as I can tell, the chart has shifted significantly.', 2, array['general_fluency', 'sh', 'ch', 'theta']),
('sentence', 'In terms of approach, I think the shortlist is solid.', 2, array['general_fluency', 'theta', 'sh', 'ending_d']),
('sentence', 'I hope that sheds some light on the situation at hand.', 1, array['general_fluency', 'sh', 'theta', 'ending_d']),
('sentence', 'If anything, this confirms the need to address the backlog.', 2, array['general_fluency', 'theta', 'ending_d', 'sh']),
('sentence', 'I think the shift we made last month was absolutely the right call.', 2, array['general_fluency', 'sh', 'theta', 'past_tense']),
('sentence', 'That being the case, I suggest we push back the third deadline.', 3, array['general_fluency', 'sh', 'theta', 'ending_d']),
('sentence', 'The third time is the charm, and I truly believe that.', 2, array['general_fluency', 'theta', 'ch', 'ending_d']),
('sentence', 'To be on the safe side, let us share the draft with the team first.', 2, array['general_fluency', 'sh', 'ending_d', 'theta']),
('sentence', 'Everything considered, the choice to switch was the right one.', 2, array['general_fluency', 'ch', 'sh', 'theta']),
('sentence', 'I will be the first to admit that this is a tough situation.', 2, array['general_fluency', 'sh', 'theta', 'ending_d']),
('sentence', 'Not only that, but the third proposal also addressed the edge cases.', 3, array['general_fluency', 'theta', 'sh', 'ending_d']),
('sentence', 'The key takeaway is that sharing early leads to better outcomes.', 2, array['general_fluency', 'sh', 'theta', 'ending_d']),
('sentence', 'Having been through this before, I know it gets better.', 2, array['general_fluency', 'theta', 'sh', 'ending_d']),
('sentence', 'On a brighter note, the third sprint showed a real breakthrough.', 3, array['general_fluency', 'theta', 'sh', 'ch']),
('sentence', 'That is the kind of thinking that shifts the whole dynamic.', 3, array['general_fluency', 'sh', 'theta', 'ending_d']),
('sentence', 'To wrap up, I think this has been a really productive session.', 2, array['general_fluency', 'sh', 'theta', 'ending_d']),
('sentence', 'I appreciate each contribution, no matter how small it seems.', 2, array['general_fluency', 'ch', 'theta', 'ending_d']),
('sentence', 'That shifts my thinking — I had not considered it that way.', 2, array['general_fluency', 'sh', 'theta', 'ending_d']),
('sentence', 'To echo what she said, the third version is much sharper.', 2, array['general_fluency', 'sh', 'theta', 'ch']),
('sentence', 'Just to be clear, I am not suggesting we skip the checks entirely.', 3, array['general_fluency', 'sh', 'ch', 'theta']),
('sentence', 'Given the circumstances, I think the team made the right call.', 2, array['general_fluency', 'theta', 'ch', 'ending_d']),
('sentence', 'I do not doubt that the approach will work with the right focus.', 2, array['general_fluency', 'theta', 'ch', 'ending_d']),
('sentence', 'Speaking of which, the checklist should have been shared earlier.', 3, array['general_fluency', 'sh', 'ch', 'theta']),
('sentence', 'This is something that needs more thought before we act.', 2, array['general_fluency', 'theta', 'sh', 'ending_d']),
('sentence', 'The short version is — ship it, get feedback, and iterate.', 2, array['general_fluency', 'sh', 'theta', 'ending_d']),
('sentence', 'I think the third option strikes the best balance overall.', 2, array['general_fluency', 'theta', 'sh', 'ending_d']),
('sentence', 'Let us not rush this — the details matter more than the speed.', 2, array['general_fluency', 'sh', 'theta', 'ending_d']),
('sentence', 'I would like to think that the chosen path leads somewhere meaningful.', 3, array['general_fluency', 'theta', 'sh', 'ch']),
('sentence', 'At the same time, I think we should acknowledge the challenges ahead.', 3, array['general_fluency', 'theta', 'ch', 'sh']),
('sentence', 'If that is the case, then we should revisit the third assumption.', 3, array['general_fluency', 'theta', 'sh', 'ch']),
('sentence', 'This brings me to my final point — consistency is everything.', 2, array['general_fluency', 'theta', 'sh', 'ch']),
('sentence', 'On that note, I think we should wrap up and share next steps.', 2, array['general_fluency', 'sh', 'theta', 'ending_d']),
('sentence', 'I believe the strongest ideas are the ones that survive honest scrutiny.', 3, array['general_fluency', 'sh', 'theta', 'ending_d']),
('sentence', 'The achievement we shared as a team makes the hard work worthwhile.', 2, array['general_fluency', 'sh', 'ch', 'theta']),
('sentence', 'She thanked the whole department and wished them continued success.', 2, array['work', 'theta', 'sh', 'past_tense']),
('sentence', 'He switched to a new framework after the third production incident.', 3, array['devops', 'sh', 'ch', 'theta']),
('sentence', 'I think the shortest path to improvement is consistent, focused effort.', 2, array['general_fluency', 'sh', 'theta', 'ending_t']),
('sentence', 'The feedback was shared with the whole team after the post-mortem.', 2, array['work', 'sh', 'theta', 'past_tense']);
