insert into items (type, content, difficulty, tags) values
  ('sentence', 'I deployed the fix to production yesterday.', 1, array['past_tense', 'devops', 'ending_d']),
  ('sentence', 'I debugged the failing job before lunch.', 2, array['past_tense', 'devops', 'ending_d']),
  ('sentence', 'I configured the load balancer for the new service.', 2, array['past_tense', 'cloud', 'ending_d']),
  ('sentence', 'I merged the pull request after the tests passed.', 2, array['past_tense', 'devops', 'ending_d']),
  ('sentence', 'I reviewed the alert policy with the team.', 2, array['past_tense', 'devops', 'ending_d']),
  ('sentence', 'I fixed the cache issue in staging.', 1, array['past_tense', 'devops', 'ending_t']),
  ('sentence', 'I pushed the Docker image to the registry.', 1, array['past_tense', 'devops', 'ending_t']),
  ('sentence', 'I rolled back the release after the error rate increased.', 3, array['past_tense', 'devops', 'ending_t']),
  ('sentence', 'I monitored the database during the migration.', 2, array['past_tense', 'cloud', 'ending_d']),
  ('sentence', 'I scaled the worker pool during peak traffic.', 2, array['past_tense', 'cloud', 'ending_d']),
  ('minimal_pair', 'I walk every day. I walked yesterday.', 1, array['minimal_pair', 'past_tense', 'ending_t']),
  ('minimal_pair', 'I push code every morning. I pushed code yesterday.', 1, array['minimal_pair', 'past_tense', 'ending_t']),
  ('minimal_pair', 'I deploy on Monday. I deployed on Tuesday.', 1, array['minimal_pair', 'past_tense', 'ending_d']),
  ('minimal_pair', 'I review logs every day. I reviewed logs last night.', 2, array['minimal_pair', 'past_tense', 'ending_d']),
  ('minimal_pair', 'The job fails today. The job failed yesterday.', 2, array['minimal_pair', 'past_tense', 'ending_d']),
  ('sentence', 'I think the cache is broken.', 2, array['theta', 'devops']),
  ('sentence', 'The third thread timed out.', 3, array['theta', 'devops']),
  ('sentence', 'She checked the shell script.', 2, array['sh', 'ch', 'devops']),
  ('sentence', 'The change should ship after review.', 3, array['sh', 'ch', 'devops']),
  ('sentence', 'Which shard handled the checkout request?', 3, array['ch', 'sh', 'cloud']),
  ('sentence', 'I cooked rice and washed the dishes.', 1, array['daily', 'past_tense', 'ending_t', 'ending_d']),
  ('sentence', 'She cleaned the room and closed the windows.', 1, array['daily', 'past_tense', 'ending_d', 'plural_s']),
  ('sentence', 'I bought snacks for my friends.', 2, array['daily', 'ending_t', 'ending_s', 'plural_s']),
  ('sentence', 'The bus stops near my house.', 2, array['daily', 'ending_s', 'plural_s']),
  ('sentence', 'I watched three short shows last night.', 2, array['daily', 'ch', 'sh', 'theta', 'past_tense']),
  ('sentence', 'I booked a flight and packed two bags.', 2, array['travel', 'past_tense', 'ending_t', 'plural_s']),
  ('sentence', 'The hotel charged extra fees.', 2, array['travel', 'ch', 'past_tense', 'ending_d', 'plural_s']),
  ('sentence', 'I asked for directions at the station.', 2, array['travel', 'ending_t', 'ending_s', 'theta']),
  ('sentence', 'This beach has soft white sand.', 2, array['travel', 'theta', 'ch', 'sh', 'ending_d']),
  ('sentence', 'We changed seats before the plane took off.', 3, array['travel', 'ch', 'past_tense', 'ending_d', 'ending_s']),
  ('sentence', 'I joined the meeting five minutes late.', 1, array['work', 'meetings', 'past_tense', 'ending_d', 'ending_s']),
  ('sentence', 'Please share the charts after lunch.', 2, array['work', 'meetings', 'sh', 'ch', 'ending_s']),
  ('sentence', 'I discussed the next steps with the team.', 2, array['work', 'meetings', 'past_tense', 'ending_t', 'ending_s', 'theta']),
  ('sentence', 'The client asked three questions.', 2, array['work', 'meetings', 'ending_t', 'theta', 'ch', 'plural_s']),
  ('sentence', 'I finished the report and sent the slides.', 2, array['work', 'meetings', 'past_tense', 'sh', 'ending_t', 'ending_d', 'plural_s']),
  ('sentence', 'I worked on three projects last year.', 2, array['interviews', 'past_tense', 'ending_t', 'theta', 'plural_s']),
  ('sentence', 'I improved the process and reduced costs.', 3, array['interviews', 'past_tense', 'ending_d', 'ending_t', 'plural_s']),
  ('sentence', 'My strengths are ownership and clear communication.', 3, array['interviews', 'theta', 'sh']),
  ('sentence', 'I solved a production issue under pressure.', 3, array['interviews', 'past_tense', 'ending_d', 'sh']),
  ('sentence', 'I managed tasks across three teams.', 2, array['interviews', 'past_tense', 'ending_d', 'ending_s', 'theta']);
